### ISSUE TITLE
Machine list empty and error message on machine startup with VirtualBox 5.0 Beta 2

### ISSUE THREAD

**Issue by GreenReaper** [toptensoftware/VBoxHeadlessTray#15]
The current build fails to list any machines when [VirtualBox 5.0 Beta 2](http://dlc-cdn.sun.com/virtualbox/5.0.0_BETA2/index.html) is installed, and attempting to start a machine on the command line results in the error "No such interface supported", although the machine is in fact started and runs normally.

**Comment by mattiad** [comment]
I can confirm the bug!

**Comment by stevo-knievo** [comment]
same for [VirtualBox 5.0 Beta 3](http://dlc-cdn.sun.com/virtualbox/5.0.0_BETA3/index.html)

**Comment by jkroepke** [comment]
Some for [VirtualBox 5.0 Release](https://www.virtualbox.org/wiki/Downloads)

**Comment by stevo-knievo** [comment]
1+

**Comment by volikag** [comment]
Need updated version for new VirtualBox 5.0 Release

**Comment by GreenReaper** [comment]
This was fixed a while back. However, the issue has reoccurred with #20.
