### ISSUE TITLE
Cleanup old configuration

### ISSUE THREAD

**Issue by morlandi** [toptensoftware/VBoxHeadlessTray#32]
Hello, thank you for this great project.

After Windows update, I had to upgrade Virtualbox to v 6.1.
Then, I upgraded VBoxHeadlessTray as well (a manual uninstall of the previous version was necessary).

Now everything works as excepted, but after Windows startup the following annoing error message pops up:

```
"VBoxHeadlessTray":
Machine "nbox3 not found - Could not find a registered machine named 'nbox3'
```

I'm sure this is caused by a previous configuration since this "nbox3" VM doesn't exist any more.
Uninstalling and reinstalling VBoxHeadlessTray didn't help.
I searched for either "VBoxHeadlessTray" and "ToptenSoftware" in the Registry with no luck.

Any suggestion on how to fix this ?

**Comment by toptensoftware** [comment]
Testing my memory here, but I think what might be happening is that VBHT creates a registry entry in the auto start program area or the registry to launch itself and passes the name of the machine on the command line.

To fix this, all you should need to do is close that instance of VBHT and then start a new instance and select the new machine name.
