### ISSUE TITLE
Be able to remove instances

### ISSUE THREAD

**Issue by aussiDavid** [toptensoftware/VBoxHeadlessTray#33]
**Persona**
As a user, I would like to be able to view current instances, so that I can remove them if I no longer want to use the virtual machine.

**Purpose**
Similar to #32, I had accidentally created an instance to a server that never existed. Every time I log in, I would get these error messages with no way to resolve the issue.
![image](https://user-images.githubusercontent.com/5856280/103143698-b2b1c680-476b-11eb-995d-6f4ba88aa29a.png)

**Implementation**
1. Show a list of registered instances (see red lines in screenshot)
2. Add a remove button (see red box in screenshot)
![image](https://user-images.githubusercontent.com/5856280/103143674-46cf5e00-476b-11eb-8a34-90fa95be8279.png)

**Implementation Drawbacks**
None that I'm aware of.

**Alternate Solution**
I was able to resolve this issue by digging around in the registry.

1. Open Registry Editor (Start + R, then type regedit)
2. Navigate to the `Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run` registry.
I found this registry by searching for "vboxheadlesstray". It was the second item for me.
3. Right-click and delete the instance
![image](https://user-images.githubusercontent.com/5856280/103143741-9e21fe00-476c-11eb-9174-7c8fcb2ce803.png)

**Comment by toptensoftware** [comment]
Thanks for reporting.  Yep, this is an issue and currently the best fix is as you've described removing the registry entry.

Another interim solution would be to create a new VM in VirtualBox with the missing name (don't both installing an OS) then when you restart the tray icon will appear, you can exit it and that which will remove the registry entries.

As for a correct solution I think the best would be to update the prompt about the missing machine to give the option to remove the registry entry.

**Comment by toptensoftware** [comment]
Latest build addresses this.

You'll get the same error message as before:

![image](https://user-images.githubusercontent.com/179862/103494075-2436f680-4e89-11eb-9f02-d96cb130a3ec.png)

Followed by this prompt:

![image](https://user-images.githubusercontent.com/179862/103494097-344ed600-4e89-11eb-994f-85576940ba43.png)

Choose "No" and the auto start entries will be removed.

Fixed in the 610 Installer here: http://www.toptensoftware.com/vboxheadlesstray
