### ISSUE TITLE
Tray icon tooltip shows wrong state.

### ISSUE THREAD

**Issue by adhawkins** [toptensoftware/VBoxHeadlessTray#36]
Windows 10 Pro 22H2 19045.2846
VBoxHeadlessTray v7.0.0
Virtualbox v7.0.6 r155176 (Qt5.15.2)

The tray icon for VBoxHeadlessTray shows the wrong state in the tooltip. For example, at the moment the VM is running, but the tooltip shows:

Paused (pid: 32960)

**Comment by toptensoftware** [comment]
Thanks for reporting, but I've found the VirtualBox API almost unusable in later versions and no longer supporting this app.  If you can figure it out and send a pull request I'll happily merge it.

**Comment by adhawkins** [comment]
Understood. Will take a look and see if I can make any progress.

**Comment by shodanx2** [comment]
This should remain open, as the problem is not fixed. 
Even if the issue is Virtualbox's fault.
